import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import React, { useEffect, useRef } from 'react'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-2.png"
import { useInView, useMotionValue, useSpring } from 'framer-motion'
import Skills from '@/components/Skills'
import Experience from '@/components/Experience'
import Education from '@/components/Education'
import Certificates from '@/components/Certificates'
import Publications from '@/components/Publications'
import TransitionEffect from '@/components/TransitionEffect'

const AnimatedNumbers = ({value})=>{
    const ref = useRef(null);
    const motionValue = useMotionValue(0);
    const springValue = useSpring(motionValue,{duration:3000})
    const isInView = useInView(ref,{once:true});

    useEffect(()=>{
        if(isInView){
            motionValue.set(value);
        }
    },[isInView,value,motionValue])

    useEffect(()=>{
        springValue.on("change",(latest)=>{
            if(ref.current && latest.toFixed(0)<= value){
                ref.current.textContent = latest.toFixed(0);
            }
        })
    },[springValue,value])

    return <span ref={ref}></span>
}

const about = () => {
  return (
    <>
    <Head>
        <title>About | PATHIRAJAGE DON DINUK</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
    <TransitionEffect/>
    <main className='flex w-full flex-col items-center justify-center dark:text-light bg-light dark:bg-dark'>
        <Layout className='pt-16 px-16 sm:px-4'>
            <AnimatedText text="ENGINEER THE FUTURE." className='mb-24 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-12 !font-black uppercase tracking-tighter text-dark dark:text-light text-center'/>
            
            {/* Bold Asymmetrical Layout */}
            <div className='grid w-full grid-cols-8 gap-y-16 gap-x-12 sm:gap-x-0 sm:gap-y-12 bg-white dark:bg-dark border-4 border-dark dark:border-light p-12 sm:p-4 shadow-[16px_16px_0px_0px_rgba(182,62,150,1)] dark:shadow-[8px_8px_0px_0px_rgba(88,230,217,1)] relative'>
                
                {/* Biography Section */}
                <div className='col-span-4 flex flex-col items-start justify-start xl:col-span-8 md:order-2 space-y-8 pr-8 xl:pr-0 sm:w-full overflow-hidden'>
                    <div className="w-16 h-4 bg-primary dark:bg-primaryDark mb-2"></div>
                    <h2 className='text-4xl font-black uppercase text-dark dark:text-light tracking-widest'>Professional Summary</h2>
                    <div className='font-semibold text-dark/80 dark:text-light/80 leading-loose text-lg text-justify border-l-4 border-primary dark:border-primaryDark pl-6 py-2'>
                        <p className="mb-4">
                            Computer Engineering Graduate from the University of Ruhuna and Software Engineer with over a year of industry experience in full-stack development and scalable system architecture. 
                        </p>
                        <p className="mb-4">
                            I specialize in building robust backend systems using Java (Spring Boot), Node.js, and PHP (Laravel), with a strong focus on microservices and production-grade deployments. My expertise expands into designing automated data pipelines to transition Machine Learning models from R&D to live deployment using Docker.
                        </p>
                        <p>
                            Experienced in managing the end-to-end SDLC, optimizing SQL databases, and implementing cloud-native applications on Azure and AWS. I am seeking a Software Engineer role to leverage my expertise in systems engineering, API development, and DevOps to solve complex business challenges.
                        </p>
                    </div>

                    {/* Honors and Awards inline */}
                    <div className="mt-8 w-full">
                        <h3 className="text-2xl font-bold uppercase text-dark dark:text-light mb-6 flex items-center gap-4">
                           <span className="w-8 h-1 bg-dark dark:bg-light inline-block"></span> Honors & Awards
                        </h3>
                        <ul className="space-y-4 font-medium text-lg list-disc list-inside text-dark/80 dark:text-light/80">
                            <li><strong className="text-dark dark:text-white">First Runner-Up</strong> — Mobitel Code Blast (SLT Mobitel, 2025)</li>
                            <li><strong className="text-dark dark:text-white">Finalist</strong> — IEEE Sri Lanka Section FYP Arena (2025)</li>
                            <li><strong className="text-dark dark:text-white">Top 8 Finalist</strong> — CODE WITH WIE (IEEE WIE, 2025)</li>
                            <li><strong className="text-dark dark:text-white">Second Runners-Up</strong> — Futurum 2.0 (Univ. of Sri Jayewardenepura, 2025)</li>
                            <li><strong className="text-dark dark:text-white">Best Performer in AI & Web Dev</strong> — Apps Technologies (2024)</li>
                        </ul>
                    </div>
                </div>

                 {/* Profile Image - Bold Graphic Container */}
                 <div className='col-span-4 relative h-max rounded-none border-8 border-solid border-dark dark:border-light bg-light dark:bg-dark xl:col-span-8 md:order-1 sm:border-4 p-4 shadow-[12px_12px_0px_0px_rgba(0,0,0,1)] dark:shadow-[8px_8px_0px_0px_rgba(255,255,255,1)] ml-8 xl:ml-0 overflow-hidden w-full'>
                        <Image src={profilePic} alt="Pathirajage Don Dinuk Profile Picture" className='w-full h-auto object-cover transition-all duration-500' priority sizes='(max-width:768px) 100vw,(max-width:1200px) 50vw,50vw'/>
                 </div>
            </div>
            
            <div className="mt-32 w-full h-[2px] bg-dark dark:bg-light opacity-20"></div>

            <div className="mt-20">
              <Skills/>
            </div>
            <Experience/>
            <Education/>
            <Certificates/>
            <Publications/>
            
        </Layout>
    </main>
    </>
  )
}

export default about