import React from 'react'
import Head from 'next/head'
import Layout from '@/components/Layout'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import Image from 'next/image'
import article1 from "../../public/images/articles/article1.png"
import article2 from "../../public/images/articles/article2.png"
import article3 from "../../public/images/articles/article3.png"
import article4 from "../../public/images/articles/article4.png"
import article5 from "../../public/images/articles/article5.png"

import { motion } from 'framer-motion'
import TransitionEffect from '@/components/TransitionEffect'

const FramerImage = motion(Image);

const FeaturedArticle = ({img,title,time,summary,link})=>{
    return(
        <li className='relative col-span-1 w-full h-full flex flex-col items-center justify-start p-8 bg-light/30 backdrop-blur-md rounded-3xl dark:bg-dark/30 shadow-[0_8px_30px_rgb(0,0,0,0.04)] dark:shadow-[0_8px_30px_rgb(255,255,255,0.02)] border border-white/40 dark:border-white/10 group hover:shadow-[0_8px_30px_rgb(0,0,0,0.12)] dark:hover:shadow-[0_8px_30px_rgb(255,255,255,0.06)] transition-all duration-300'>
            
            {/* Subtle glow effect behind cards on hover */}
            <div className='absolute -inset-0.5 bg-gradient-to-r from-primary/20 to-primaryDark/20 rounded-3xl blur opacity-0 group-hover:opacity-100 transition duration-500 -z-10'></div>

            <Link href={link} target='_blank'
            className='w-full inline-block cursor-pointer overflow-hidden rounded-2xl shadow-sm mb-6'>
                <FramerImage src={img} alt={title} className='w-full h-full aspect-video object-contain hover:scale-105 transition-transform duration-500' priority sizes='(max-width:768px) 100vw,(max-width:1200px) 50vw,50vw' />
            </Link>
            
            <div className='w-full flex flex-col flex-grow items-start justify-between'>
                <div className='w-full'>
                    <Link href={link} target='_blank'>
                        <h2 className='capitalize text-2xl font-extrabold my-2 text-dark hover:text-primary dark:text-light dark:hover:text-primaryDark transition-colors xs:text-lg tracking-tight'>{title}</h2>
                    </Link>
                    <p className='text-md font-medium text-dark/70 dark:text-light/70 mb-4 xs:hidden leading-relaxed'>
                        {summary}
                    </p>
                </div>
                
                <div className='mt-6 w-full flex items-center justify-between'>
                    <span className='inline-flex items-center px-3 py-1 rounded-full text-xs font-bold tracking-widest uppercase bg-primary/10 text-primary dark:bg-primaryDark/10 dark:text-primaryDark border border-primary/20 dark:border-primaryDark/20'>
                        {time}
                    </span>
                    <Link href={link} target='_blank' className='text-sm font-semibold text-dark/50 hover:text-primary dark:text-light/50 dark:hover:text-primaryDark transition-colors group-hover:underline decoration-2 underline-offset-4 decoration-primary/50'>
                        Read Article &rarr;
                    </Link>
                </div>
            </div>
        </li>
    )
}

const articles = () => {
  return (
    <>
        <Head>
        <title>Articles Page</title>
        <meta name="description" content="Generated by create next app" />
        </Head>
        <TransitionEffect/>
        <main className='w-full min-h-screen mb-16 flex flex-col items-center justify-center overflow-hidden px-10 dark:text-light relative'>
            
            {/* Subtle animated background gradients */}
            <div className="absolute top-20 right-20 w-80 h-80 bg-rose-300/20 rounded-full mix-blend-multiply filter blur-3xl opacity-50 animate-blob dark:bg-rose-900/20 z-0 hidden lg:block" />
            <div className="absolute top-80 left-20 w-96 h-96 bg-cyan-300/20 rounded-full mix-blend-multiply filter blur-3xl opacity-50 animate-blob animation-delay-4000 dark:bg-cyan-900/20 z-0 hidden lg:block" />

            <Layout className='pt-16 z-10 relative'>
                <AnimatedText text="Insights & Thoughts" className='mb-16 lg:!text-6xl sm:mb-8 sm:!text-5xl xs:!text-4xl text-transparent bg-clip-text bg-gradient-to-r from-primary to-primaryDark drop-shadow-sm'/>
                <ul className='grid grid-cols-2 gap-12 lg:gap-8 md:grid-cols-1 md:gap-y-16' >
                    <FeaturedArticle
                    title="What is Prompt Engineering?"
                    summary="An introduction to prompt engineering, exploring how to craft effective prompts to interact with large language models efficiently."
                    time="6 min read"
                    img={article1}
                    link="https://medium.com/@pathirajadnew/what-is-prompt-engineering-c8c082aecc25"/>
                    
                    <FeaturedArticle
                    title="ML Zero to Hero - Part 1"
                    summary="A comprehensive guide to getting started with Machine Learning covering the fundamental concepts and basic algorithms."
                    time="4 min read"
                    img={article2}
                    link="https://medium.com/@pathirajadnew/ml-zero-to-hero-part-1-905d7993318b"/>

                    <FeaturedArticle
                    title="ML Zero to Hero - Part 2"
                    summary="Diving deeper into Machine Learning models, evaluation metrics, and practical implementations."
                    time="5 min read"
                    img={article3}
                    link="https://medium.com/@pathirajadnew/ml-zero-to-hero-part-2-1c68e173a71b"/>

                    <FeaturedArticle
                    title="ML Zero to Hero - Part 3"
                    summary="Advanced concepts in the ML Zero to Hero series, focusing on complex architectures and fine-tuning."
                    time="4 min read"
                    img={article4}
                    link="https://medium.com/@pathirajadnew/ml-zero-to-hero-part-2-6419bf0f6e58"/>

                    <FeaturedArticle
                    title="Guide to Deploying Ollama on AWS EC2"
                    summary="A step-by-step guide to deploying and accessing Ollama instances securely on Amazon Web Services EC2 infrastructure."
                    time="3 min read"
                    img={article5}
                    link="https://medium.com/@pathirajadnew/guide-to-deploying-and-accessing-ollama-on-aws-ec2-c0ee3c1d9fc4"/>
                </ul>
            </Layout>
        </main>
    </>
  )
}

export default articles