import Head from "next/head";
import Layout from "@/components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import lightrobot from "../../public/images/lightrobot.png";
import darkrobot from "../../public/images/darkrobot.png";
import useThemeSwitcher from "@/components/hooks/useThemeSwitcher";

export default function Home() {
  const [mode, setMode] = useThemeSwitcher();
  return (
    <>
      <Head>
        <title>PATHIRAJAGE DON DINUK | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light overflow-hidden bg-white dark:bg-dark transition-colors duration-300">
        
        {/* Bold Split-Screen Layout wrapper */}
        <div className="flex flex-row lg:flex-col-reverse w-full min-h-screen items-center justify-between relative z-10 mx-auto max-w-[1920px]">
          
          {/* LEFT HALF: Bold Typography and CTAs */}
          <div className="w-1/2 lg:w-full flex-1 flex flex-col justify-center items-start pl-32 xl:pl-20 lg:px-12 md:px-8 sm:px-6 lg:py-16 pt-0 z-20">
            <h2 className="text-xl md:text-lg sm:text-base font-bold tracking-[0.2em] uppercase text-primary dark:text-primaryDark mb-4">
              Computer Engineering Graduate & Software Engineer
            </h2>
            <AnimatedText
              text="PATHIRAJAGE DON DINUK."
              className="!text-7xl xl:!text-6xl lg:!text-7xl md:!text-5xl sm:!text-4xl !text-left !font-black !leading-tight text-dark dark:text-light tracking-tighter"
            />
            
            <div className="w-24 h-2 bg-primary dark:bg-primaryDark my-8 overflow-hidden relative">
                <div className="w-full h-full bg-light/30 absolute top-0 -left-full animate-[shimmer_2s_infinite]"></div>
            </div>

            <p className="mb-10 text-xl font-medium md:text-lg sm:text-base text-dark/75 dark:text-light/75 leading-relaxed max-w-2xl border-l-4 border-dark/20 dark:border-light/20 pl-6">
              I combine a robust theoretical foundation in structural systems with modern <strong className="text-dark dark:text-light">Machine Learning</strong> and <strong className="text-dark dark:text-light">Full-Stack Architecture</strong> expertise to architect the next generation of scalable software intelligence.
            </p>

            {/* Premium Solid Action Buttons */}
            <div className="flex items-center flex-wrap gap-6 w-full">
              <Link
                href="/P_D_Dinuk_SE_Resume.pdf"
                target={"_blank"}
                className="group flex items-center justify-center min-w-[160px] bg-dark text-light dark:bg-light dark:text-dark 
                p-4 px-8 squared-sm text-xl font-bold uppercase tracking-wider
                hover:bg-primary hover:text-white dark:hover:bg-primaryDark dark:hover:text-dark border-2 border-dark dark:border-light hover:border-primary dark:hover:border-primaryDark transition-all duration-300 shadow-[8px_8px_0px_0px_rgba(182,62,150,0.5)] dark:shadow-[8px_8px_0px_0px_rgba(88,230,217,0.5)] hover:shadow-[4px_4px_0px_0px_rgba(182,62,150,0.8)] dark:hover:shadow-[4px_4px_0px_0px_rgba(88,230,217,0.8)] hover:translate-x-1 hover:translate-y-1"
                download={true}
              >
                SE Resume
                <LinkArrow className="w-6 ml-3 transition-transform duration-300 group-hover:translate-x-1"></LinkArrow>
              </Link>
              <Link
                href="/P_D_Dinuk_ML_Resume.pdf"
                target={"_blank"}
                className="group flex items-center justify-center min-w-[160px] bg-dark text-light dark:bg-light dark:text-dark 
                p-4 px-8 squared-sm text-xl font-bold uppercase tracking-wider
                hover:bg-primary hover:text-white dark:hover:bg-primaryDark dark:hover:text-dark border-2 border-dark dark:border-light hover:border-primary dark:hover:border-primaryDark transition-all duration-300 shadow-[8px_8px_0px_0px_rgba(182,62,150,0.5)] dark:shadow-[8px_8px_0px_0px_rgba(88,230,217,0.5)] hover:shadow-[4px_4px_0px_0px_rgba(182,62,150,0.8)] dark:hover:shadow-[4px_4px_0px_0px_rgba(88,230,217,0.8)] hover:translate-x-1 hover:translate-y-1"
                download={true}
              >
                ML Resume
                <LinkArrow className="w-6 ml-3 transition-transform duration-300 group-hover:translate-x-1"></LinkArrow>
              </Link>

              <Link
                href="mailto:pathirajadnew@gmail.com"
                className="group flex items-center justify-center min-w-[180px] bg-transparent text-dark dark:text-light 
                p-4 px-8 squared-sm text-xl font-bold uppercase tracking-wider
                border-2 border-dark dark:border-light hover:bg-dark hover:text-light dark:hover:bg-light dark:hover:text-dark transition-all duration-300"
              >
                Let&apos;s Talk
              </Link>
            </div>
          </div>  

          {/* RIGHT HALF: Massive Edge-to-Edge Portrait */}
          <div className="w-1/2 lg:w-full h-screen lg:min-h-[50vh] relative bg-dark/5 dark:bg-light/5 flex items-end justify-center overflow-hidden border-l-8 border-primary dark:border-primaryDark lg:border-l-0 lg:border-b-8">
            <div className="absolute inset-0 bg-gradient-to-t from-white via-transparent to-transparent dark:from-dark z-10 lg:hidden"></div>
            
            {/* The actual image engineered to be massive and striking */}
            <Image
              src={profilePic}
              alt="PATHIRAJAGE DON DINUK"
              className="w-auto h-[90%] lg:h-full lg:w-full object-cover object-top relative z-0 drop-shadow-2xl hover:scale-105 transition-all duration-700 ease-in-out"
              priority
              sizes="(max-width:768px) 100vw,(max-width:1200px) 50vw,50vw"
            />
            
            {/* Optional stylistic giant typography in background of photo */}
            <div className="absolute top-10 right-10 text-[15rem] font-black leading-none text-black/5 dark:text-white/5 select-none pointer-events-none z-0 tracking-tighter">
              DO<br/>ER.
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
